# Generated by Django 2.2.3 on 2019-10-29 18:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('num_players', models.PositiveIntegerField(default=2, verbose_name='Number of players')),
            ],
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('score', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrabble.Game')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TileTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('point_value', models.IntegerField(default=0, verbose_name='Tile point value')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('games', models.ManyToManyField(through='scrabble.GamePlayer', to='scrabble.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(choices=[('BO', 'Board'), ('BA', 'Bag'), ('P1', 'Player 1'), ('P2', 'Player 2'), ('P3', 'Player 3'), ('P4', 'Player 4')], max_length=2)),
                ('position', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrabble.Game')),
                ('tile_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scrabble.TileTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='Square',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrabble.Tile')),
            ],
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrabble.User'),
        ),
        migrations.AddIndex(
            model_name='tile',
            index=models.Index(fields=['owner', 'position'], name='scrabble_ti_owner_f7a2b2_idx'),
        ),
    ]
